spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/labDB
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: false